name: Github Actions Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: dev
        run: |
          echo "PROJECT: $PROJECT"
        env:
          PROJECT: develop